spring:
  datasource:
    url: jdbc:mysql://localhost:3307/chatdb
    username: root
    password: 1234

  data:
    redis:
      host: localhost
      port: 6380

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: consumer

server:
  port: -1

logging:
  level:
    root: INFO
    org.springframework: WARN
    karrot.chat: DEBUG

